sudo: required
services:
  - docker

before_install:
  - docker build -t raulcontrerasrubio/frontend-cicd -f Dockerfile.dev .

script:
  - docker run raulcontrerasrubio/frontend-cicd npm run test-ci

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "frontend-cicd"
  env: "FrontendCicd-env"
  bucket_name: "elasticbeanstalk-us-east-2-705173592693"
  bucket_path: "frontend-cicd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"