language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t raulcontrerasrubio/frontend-cicd -f Dockerfile.dev .
script:
  - docker run -e CI=true raulcontrerasrubio/frontend-cicd npm run test