version: "3"
services:
  react-client:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/client/node_modules
      - .:/home/client